[build-system]
requires = ["setuptools >= 61.2.0", "wheel >= 0.37.1", "pytest == 7.1.2", "mypy == 0.910"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py310

[testenv]
deps = 
    pytest == 7.1.2
    mypy == 0.961
setenv = 
    PYTHONPATH = {toxinidir}/src
commands_pre = 
    python3 bootstrap/pyweb.py -o src src/pyweb.w
    python3 src/pyweb.py -o tests tests/pyweb_test.w 
commands = 
    pytest
	mypy --strict --show-error-codes src
"""
